### ISSUE TITLE
Cannot worked in Gradle 2.2.1

### ISSUE THREAD

**Issue by johnwatsondev** [eskimoapps/ResourceNestingExample#2]
<img width="678" alt="qq20150718-1" src="https://cloud.githubusercontent.com/assets/12760754/8753515/feeb234a-2cee-11e5-989c-163fb52d57d7.png">
<img width="413" alt="qq20150718-2" src="https://cloud.githubusercontent.com/assets/12760754/8753520/03fbf65c-2cef-11e5-8c72-fd1a982a436c.png">

As you see the SNAPSHOT in my project it cannot identify the layout sub folder any more!

**Comment by davebren** [comment]
The layout file still needs its direct parent to be a layout folder. Here, the 'activity' folder is being treated as a resource folder (see how the folder icon changed). Try declaring a res folder 'src/main/res/activity' and then add a layout folder, and then add the layout file to that.

**Comment by johnwatsondev** [comment]
@eskimoapps  YES. It worked. Thanks for your patient help! 

<img width="141" alt="qq20150720-1" src="https://cloud.githubusercontent.com/assets/12760754/8768728/104bcc6e-2ebd-11e5-920a-d5b85719e903.png">

**Comment by Tomblarom** [comment]
Well I'm getting exact the same problem!!

```
/src/main/res/layouts
 -- /layouts_fragment
 -- /layouts_activity
```

![img1](http://i.imgur.com/LbWz8iP.png)
![img2](http://i.imgur.com/43BGFhI.png)
![img3](http://i.imgur.com/xLweoHr.png)

**Comment by Tomblarom** [comment]
"Try declaring a res folder 'src/main/res/activity' and then **add a layout folder**, and then **add the layout file** to that." -  Sorry ;)
