### ISSUE TITLE
Please read the migration guide to learn how to update your project.

### ISSUE THREAD

**Issue by kamilwlf** [eskimoapps/ResourceNestingExample#3]
The project is using an unsupported version of the Android Gradle plug-in (0.7.3). The recommended version is 1.3.0. Starting with version 0.9.0 incompatible changes were introduced in the build language. Please read the migration guide to learn how to update your project.

**Comment by davebren** [comment]
Pull requests are welcome!

**Comment by davebren** [comment]
I've created issue https://github.com/eskimoapps/ResourceNestingExample/issues/4 for updating the project to a newer version of gradle/AS.
